<h1><center><font color = "red">Data Preprocessing</font></h1>

<h3><font color = "green">Load Necessary Libraries</font></h3>

In [1]:
# important libraries
import pandas as pd
import numpy as np
import warnings
import os

# display all features
pd.set_option("display.max_columns", None)

# filter warnings
warnings.filterwarnings(action="ignore")

<h3><font color = "green">Load and Display Dataset</font></h3>

In [2]:
DATASETS_file = "../cleaning"
csv_file = "accidents_df_cleaned.csv"

csv_file_path = os.path.join(DATASETS_file, csv_file)
accidents_df = pd.read_csv(filepath_or_buffer=csv_file_path)

print(f"accidents_df shape:\t{accidents_df.shape}")
accidents_df.head()

accidents_df shape:	(1370980, 44)

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Street,Side,City,County,State,Zipcode,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-2716600,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,40.112060,-83.031870,3.230,Outerbelt E,R,Dublin,Franklin,OH,43017,US/Eastern,KOSU,2016-02-08 00:53:00,42.1,36.1,58.0,29.76,10.0,SW,10.4,0.00,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2716605,3,2016-02-08 07:53:43,2016-02-08 13:53:43,39.172393,-84.492792,39.170476,-84.501798,0.500,I-75 S,R,Cincinnati,Hamilton,OH,45217,US/Eastern,KLUK,2016-02-08 07:53:00,37.0,29.8,93.0,29.69,10.0,WSW,10.4,0.01,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
2,A-2716606,2,2016-02-08 08:16:57,2016-02-08 14:16:57,39.063240,-84.032430,39.067310,-84.058510,1.427,State Route 32,R,Williamsburg,Clermont,OH,45176,US/Eastern,KI69,2016-02-08 08:16:00,35.6,29.2,100.0,29.66,10.0,WSW,8.1,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day
3,A-2716607,2,2016-02-08 08:16:57,2016-02-08 14:16:57,39.067080,-84.058550,39.063020,-84.032540,1.423,State Route 32,R,Batavia,Clermont,OH,45103,US/Eastern,KI69,2016-02-08 08:16:00,35.6,29.2,100.0,29.66,10.0,WSW,8.1,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
4,A-2716608,2,2016-02-08 08:15:41,2016-02-08 14:15:41,39.775650,-84.186030,39.772750,-84.188050,0.227,I-75 S,R,Dayton,Montgomery,OH,45404,US/Eastern,KFFO,2016-02-08 08:18:00,33.8,NaN,100.0,29.63,3.0,SW,2.3,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day

<h3><font color = "green">General Informations</font></h3>

In [3]:
# Check for data types 
accidents_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1370980 entries, 0 to 1370979
Data columns (total 44 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   ID                     1370980 non-null  object
 1   Severity               1370980 non-null  int64
 2   Start_Time             1370980 non-null  object
 3   End_Time               1370980 non-null  object
 4   Start_Lat              1370980 non-null  float64
 5   Start_Lng              1370980 non-null  float64
 6   End_Lat                1370980 non-null  float64
 7   End_Lng                1370980 non-null  float64
 8   Distance(mi)           1370980 non-null  float64
 9   Street                 1370980 non-null  object
 10  Side                   1370980 non-null  object
 11  City                   1370980 non-null  object
 12  County                 1370980 non-null  object
 13  State                  1370980 non-null  object
 14  Zipcode                1370980 non-null  object
 15  Timezone               1370980 non-null  object
 16  Airport_Code           1370980 non-null  object
 17  Weather_Timestamp      1370980 non-null  object
 18  Temperature(F)         1370980 non-null  float64
 19  Wind_Chill(F)          1058853 non-null  float64
 20  Humidity(%)            1370980 non-null  float64
 21  Pressure(in)           1370980 non-null  float64
 22  Visibility(mi)         1370980 non-null  float64
 23  Wind_Direction         1370980 non-null  object
 24  Wind_Speed(mph)        1370980 non-null  float64
 25  Precipitation(in)      976579 non-null   float64
 26  Weather_Condition      1370980 non-null  object
 27  Amenity                1370980 non-null  bool
 28  Bump                   1370980 non-null  bool
 29  Crossing               1370980 non-null  bool
 30  Give_Way               1370980 non-null  bool
 31  Junction               1370980 non-null  bool
 32  No_Exit                1370980 non-null  bool
 33  Railway                1370980 non-null  bool
 34  Roundabout             1370980 non-null  bool
 35  Station                1370980 non-null  bool
 36  Stop                   1370980 non-null  bool
 37  Traffic_Calming        1370980 non-null  bool
 38  Traffic_Signal         1370980 non-null  bool
 39  Turning_Loop           1370980 non-null  bool
 40  Sunrise_Sunset         1370980 non-null  object
 41  Civil_Twilight         1370980 non-null  object
 42  Nautical_Twilight      1370980 non-null  object
 43  Astronomical_Twilight  1370980 non-null  object
dtypes: bool(13), float64(12), int64(1), object(18)
memory usage: 341.2+ MB

In [4]:
# Check statistics
accidents_df.describe()

,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
count,1.370980e+06,1.370980e+06,1.370980e+06,1.370980e+06,1.370980e+06,1.370980e+06,1.370980e+06,1.058853e+06,1.370980e+06,1.370980e+06,1.370980e+06,1.370980e+06,976579.000000
mean,2.223431e+00,3.687072e+01,-9.858667e+01,3.687078e+01,-9.858647e+01,5.744937e-01,5.979587e+01,5.515266e+01,6.420014e+01,2.952813e+01,9.145091e+00,7.631396e+00,0.007644
std,5.951861e-01,5.202776e+00,1.846727e+01,5.202751e+00,1.846714e+01,1.612182e+00,1.824638e+01,2.110355e+01,2.322987e+01,1.030335e+00,2.795097e+00,5.600232e+00,0.100136
min,1.000000e+00,2.457022e+01,-1.244976e+02,2.457011e+01,-1.244978e+02,0.000000e+00,-2.900000e+01,-5.900000e+01,1.000000e+00,2.000000e-02,0.000000e+00,0.000000e+00,0.000000
25%,2.000000e+00,3.383234e+01,-1.182171e+02,3.383233e+01,-1.182171e+02,0.000000e+00,4.800000e+01,4.100000e+01,4.800000e+01,2.940000e+01,1.000000e+01,4.600000e+00,0.000000
50%,2.000000e+00,3.732941e+01,-9.409633e+01,3.732943e+01,-9.409387e+01,1.620000e-01,6.100000e+01,5.700000e+01,6.700000e+01,2.986000e+01,1.000000e+01,7.000000e+00,0.000000
75%,2.000000e+00,4.073800e+01,-8.092084e+01,4.073834e+01,-8.092127e+01,5.850000e-01,7.340000e+01,7.100000e+01,8.400000e+01,3.003000e+01,1.000000e+01,1.040000e+01,0.000000
max,4.000000e+00,4.900058e+01,-6.711317e+01,4.907500e+01,-6.710924e+01,1.551860e+02,1.706000e+02,1.130000e+02,1.000000e+02,5.804000e+01,1.110000e+02,9.840000e+02,24.000000

<h3><font color = "green">Data Preprocessing</font></h3>

The data will pass through the following processes and transformations:
<br></br>
* Lists of numerical boolean, and categorical (>2 categories) features.
* Convert boolean objects to numerical values 0 and 1.
* Convert Start_Time and End_Time to timestamps using pd.to_datetime.
* Add additional columns for starting hour, day_of_week, month and year, date.
* Add an additional column named "Count" equal to 1, for analysis reasons.

In [5]:
# Numerical, boolean and categorical lists of features
bol_cols = [col for col in accidents_df.columns if accidents_df[col].dtype == object and accidents_df[col].nunique() == 2]
cat_cols = [col for col in accidents_df.columns if accidents_df[col].dtype == object and accidents_df[col].nunique() > 2]
num_cols = [col for col in accidents_df.columns if accidents_df[col].dtype != object]

In [6]:
### Convert boolean objects to numerical values.

## We will change the 4 features with same categories ("Day", "Night") together and the feature "Side" seperately.

# Convert "Sunrise_Sunset", "Civil_Twilight", "Nautical_Twilight", and "Astronomical_Twilight" features
accidents_df[bol_cols[1:]] = accidents_df[bol_cols[1:]].replace({"Day": 1, "Night": 0})

# Convert "Side" feature
accidents_df["Side"] = accidents_df["Side"].replace({"R": 1, "L": 0})

# Check the changes
accidents_df[bol_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1370980 entries, 0 to 1370979
Data columns (total 5 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Side                   1370980 non-null  int64
 1   Sunrise_Sunset         1370980 non-null  int64
 2   Civil_Twilight         1370980 non-null  int64
 3   Nautical_Twilight      1370980 non-null  int64
 4   Astronomical_Twilight  1370980 non-null  int64
dtypes: int64(5)
memory usage: 52.3 MB

In [7]:
# Convert Star_Time to timestamps
accidents_df[["Start_Time", "End_Time"]] = accidents_df[["Start_Time", "End_Time"]].apply(pd.to_datetime)

# Add columns for starting hour, day of week, month and year
accidents_df["Start_Day_Week"] = accidents_df["Start_Time"].dt.dayofweek
accidents_df["Start_Month"] = accidents_df["Start_Time"].dt.month
accidents_df["Start_Date"] = accidents_df["Start_Time"].dt.date
accidents_df["Start_Hour"] = accidents_df["Start_Time"].dt.hour
accidents_df["Start_Year"] = accidents_df["Start_Time"].dt.year

# Add the column "Count"
accidents_df["Count"] = 1

In [13]:
# Taking a sample
accidents_df = accidents_df.sample(750000)
accidents_df

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Street,Side,City,County,State,Zipcode,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Start_Day_Week,Start_Month,Start_Date,Start_Hour,Start_Year,Count
1303654,A-4169407,2,2019-04-11 08:55:50,2019-04-11 12:55:50,45.572572,-118.454999,45.591029,-118.469654,1.459,I-84 W,1,Meacham,Umatilla,OR,97859,US/Pacific,KMEH,2019-04-11 08:56:00,35.0,35.0,89.0,26.18,1.0,CALM,0.0,0.10,Light Snow,False,False,False,False,False,False,False,False,False,False,False,False,False,1,1,1,1,3,4,2019-04-11,8,2019,1
209727,A-2969311,2,2020-10-02 13:47:00,2020-10-02 15:01:30,30.320775,-81.689334,30.321883,-81.697011,0.464,FL-228 W,1,Jacksonville,Duval,FL,32204,US/Eastern,KNIP,2020-10-02 13:53:00,77.0,77.0,45.0,30.00,10.0,NNW,6.0,0.00,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,1,1,1,1,4,10,2020-10-02,13,2020,1
1231635,A-4079448,3,2018-02-08 05:53:57,2018-02-08 11:53:57,45.525680,-107.417406,45.525680,-107.417406,0.000,I-90 E,1,Garryowen,Big Horn,MT,59031,US/Mountain,KM46,2018-02-08 05:53:00,11.0,-3.0,92.0,27.35,1.0,NE,10.0,0.01,Light Snow,False,False,False,False,True,False,False,False,False,False,False,False,False,0,0,0,1,3,2,2018-02-08,5,2018,1
502920,A-3282758,2,2020-11-14 10:38:00,2020-11-14 12:40:59,40.005286,-75.075684,39.996146,-75.082894,0.738,I-95 S,1,Philadelphia,Philadelphia,PA,19137,US/Eastern,KPNE,2020-11-14 10:54:00,52.0,52.0,54.0,30.08,10.0,WNW,7.0,0.00,Fair,False,False,False,False,True,False,False,False,False,False,False,True,False,1,1,1,1,5,11,2020-11-14,10,2020,1
635136,A-3423754,2,2020-10-06 06:38:22,2020-10-06 07:54:38,44.964777,-93.229240,44.964397,-93.240670,0.559,I-94 W,1,Minneapolis,Hennepin,MN,55454,US/Central,KMSP,2020-10-06 06:53:00,50.0,50.0,80.0,28.97,10.0,SSW,3.0,0.00,Fair,False,False,False,False,True,False,False,False,False,False,False,False,False,0,0,1,1,1,10,2020-10-06,6,2020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984702,A-3788487,2,2019-12-22 01:25:37,2019-12-22 05:25:37,42.054980,-124.269440,42.054980,-124.269440,0.000,Chetco Ave,1,Brookings,Curry,OR,97415,US/Pacific,KBOK,2019-12-22 01:39:00,46.0,46.0,100.0,29.25,10.0,CALM,0.0,0.02,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,6,12,2019-12-22,1,2019,1
1276723,A-4136507,2,2017-10-24 00:28:53,2017-10-24 06:28:53,40.669740,-74.178620,40.661890,-74.185210,0.643,North Ave E,1,Newark,Union,NJ,07114,US/Eastern,KEWR,2017-10-24 00:13:00,68.0,NaN,90.0,29.96,10.0,SSE,16.1,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,1,10,2017-10-24,0,2017,1
1248855,A-4100891,3,2018-01-26 15:40:50,2018-01-26 21:40:50,29.799720,-95.563650,29.797710,-95.563630,0.139,W Sam Houston Tollway S,1,Houston,Harris,TX,77043,US/Central,KMCJ,2018-01-26 15:35:00,66.2,NaN,78.0,30.18,9.0,SE,9.2,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,False,False,1,1,1,1,4,1,2018-01-26,15,2018,1
1024795,A-3830536,2,2019-11-02 22:19:00,2019-11-02 23:53:45,37.626132,-120.847779,37.626132,-120.847779,0.000,Jantzen Rd,1,Waterford,Stanislaus,CA,95386,US/Pacific,KMOD,2019-11-02 21:53:00,49.0,49.0,69.0,29.93,8.0,CALM,0.0,0.00,Fair,False,False,False,False,False,False,False,False,False,False,False,False,False,0,0,0,0,5,11,2019-11-02,22,2019,1
1267837,A-4125208,3,2017-11-22 17:19:09,2017-11-22 23:19:09,42.154080,-87.959270,42.154080,-87.959270,0.000,E Lake Cook Rd,1,Buffalo Grove,Lake,IL,60089,US/Central,KPWK,2017-11-22 16:52:00,33.1,30.0,50.0,30.29,10.0,WSW,3.5,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,True,False,0,0,1,1,2,11,2017-11-22,17,2017,1

In [14]:
# Save the preproced dataset
accidents_df.to_csv("accidents_df_preproced.csv", index=False)